### ISSUE TITLE
Great start

### ISSUE THREAD

**Issue by ThermIQ** [mvheimburg/hass-component-systemair#1]
Hi,
I just wanted to say thank you for a great start for systemair integration. I have a VSR500 and have hooked it up with an Elfin ew11 Modbus gateway and installed your integration. Worked after figuring out how to configure it, in my case:

```
modbus:
  - type: tcp
    host: 192.168.2.120
    port: 8899
    name: "SystemAir"
climate:
  - platform: systemair
    hub: "SystemAir"
    name: "VSR500"
    slave: 1

```

If you are interested I have the latest (v36) registermap converted into excel from which one could autogenerate the const.py register definition.
